community/urls.py
from django.urls import path
from . import views

app_name = 'community'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('comment/create/<int:post_id>/', views.comment_create, name='comment_create'),
    path('post/create/', views.post_create, name='post_create'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# settings.MEDIA_URL
# settings.MEDIA_ROOT

community/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    photo = models.ImageField(blank=True, upload_to='community/book/%Y%m')
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    # 쿼리에서 order_by 지정 안 했을 때, 정렬 default값
    class Meta:
        ordering = ['-id']


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

community/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']
        labels = {
            'title': '제목',
            'content': '내용',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {
            'content': '댓글내용',
        }

community/views.py
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostForm, CommentForm


def index(request):
    ps = Post.objects.all()
    # ps = Post.objects.order_by('-create_date')
    q = request.GET.get('q', '')
    if q:
        post_list = ps.filter(content__icontains=q)
    else:
        post_list = ps
    context = {'post_list': post_list, 'q': q, }
    return render(request, 'community/post_list.html', context)


def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, 'community/detail.html', context)


def comment_create(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False) # 임시저장
            comment.post = post
            comment.save()
            return redirect('community:detail', post_id=post.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible')
    context = {'post': post, 'form': form}
    return render(request, 'community/detail.html', context)


def post_create(request):
    # 글 작성을 위해 POST 요청
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('community:index')
    else: # GET 요청
        form = PostForm() # empty form
    context = {'form': form}
    return render(request, 'community/post_form.html', context)


# def post_list(request):
#     qs = Post.objects.all()
#     q = request.GET.get('q', '')
#     # q에 해당하는 검색어가 있다면
#     if q:
#         qs = qs.filter(content__icontains=q)
#     # ~/templates/community/post_list.html
#     return render(request, 'community/post_list.html', {
#         'post_list': qs,
#     })

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Title</title>
</head>
<!-- 부트스트랩 JS-->
<script src="{% static 'bootstrap.min.js' %}"></script>
<body>
<!-- 네비게이션바 -->
{% include 'navbar.html' %}
{% block content%}
{% endblock %}
</body>
</html>

templates/community/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 게시글 -->
    <h2 class="border-bottom py-2">{{ post.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ post.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ post.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">댓글 {{ post.comment_set.count }}</h5>
    {% for comment in post.comment_set.all %}
    <div class="card my-1">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ comment.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-1">
                    {{ comment.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
<!-- 답변 등록 폼 -->
<form action="{% url 'community:comment_create' post.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">댓글내용</label>
            <textarea name="content" id="content" class="form-control" rows="4"></textarea>
        </div>
        <input type="submit" value="댓글등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/community/post_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">글 작성</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="title" class="form-label">제목</label>
            <input type="text" class="form-control" name="title" id="title"
                   value="{{ form.title.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/community/post_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-2">
    <table class="table">

        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if post_list %}
        {% for post in post_list %}
        <tr>
            <td>{{ forloop.counter }}</td>  <!-- 번호 -->
            <td> <!-- 제목 -->
                <a href="{% url 'community:detail' post.id %}">{{ post.title }}</a>
            </td> <!-- 작성일자 -->
            <td>{{ post.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">해당 게시글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <div>
        <a href="{% url 'community:post_create' %}" class="btn btn-primary">글 작성</a>
        <form action="" class="d-flex" role="search">
            <input class="form-control me-2" type="search" name="q" value="{{ q }}"
                   placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
</div>
{% endblock %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Brandname</a>
    <button class="navbar-toggler" type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Community</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search"
               placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#">로그인</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">회원가입</a>
        </li>
      </ul>
    </div>
  </div>
</nav>